In [13]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns   
import sklearn

import pandas as pd

In [17]:
base_navios = pd.read_csv('Dados navios Hackathon.xlsx - Dados navios.csv')
base_eventos = pd.read_csv('Relatorios IWS.xlsx - Planilha1.csv')
resultado_consumo = pd.read_csv('ResultadoQueryConsumo.csv')
resultado_eventos = pd.read_csv('ResultadoQueryEventos.csv')

base_navios.head()

,Nome do navio,Classe,Tipo,Porte Bruto,Comprimento total (m),Boca (m),Calado (m),Pontal (m)
0,RAFAEL SANTOS,Suezmax,Petroleiro,156628,"274,2",48,17,"23,2"
1,HENRIQUE ALVES,Suezmax,Petroleiro,157700,"274,2",48,17,"23,2"
2,VICTOR OLIVEIRA,Suezmax,Petroleiro,156492,"274,2",48,17,"23,2"
3,FELIPE RIBEIRO,Suezmax,Petroleiro,157700,"274,2",48,17,"23,2"
4,GISELLE CARVALHO,Suezmax,Petroleiro,156504,"274,2",48,17,"23,2"

In [21]:
base_eventos.head()

,Classe,Embarcação,Sigla,Data,Local de realização,Regiões do casco limpas,Condição geral da embarcação,Tipo de incrustação da embarcação,Condição do fundo chato,Tipo de incrustação do fundo chato,Condição do costado,Tipo de incrustação do costado,Condição do hélice,Tipo de incrustação do hélice
0,Aframax,Carla Silva,CSI,8/29/2025,Angra dos Reis/RJ,NaN,100%,"Craca, alga e limo",100%,Incrustações duras e moles,"100%, 20%",Moles (100%) e Duras (20%),100%,Moles e Duras
1,Suezmax,Raul Martins,RMA,3/30/2023,São Sebastião/SP,NaN,10%,Duras no fundo,10%,Duras,Não consta no relatório,Não consta no relatório,40%,Moles e Duras
2,MR2,Eduardo Costa,EDC,1/11/2025,São Sebastião/SP,NaN,10%,Moles e duras,10%,Moles (5%) e Duras (5%),5%,Moles,80%,Moles
3,Suezmax,Victor Oliveira,VOL,3/3/2021,Salvador/BA,NaN,30%,Cracas e limo,30%,Cracas e limo,30%,Cracas e limo,90%,Cracas e limo
4,Aframax,Carla Silva,CSI,8/21/2021,Angra dos Reis/RJ,NaN,100%,Alga e limo,100%,Alga e limo,100%,Alga e limo,85%,"Alga, limo e calcárea"

In [16]:
resultado_consumo.head()

    SESSION_ID  CONSUMED_QUANTITY DESCRIPTION
0  39800000086               47.0   LSHFO 0.5
1  39800000088               48.0   LSHFO 0.5
2  39800000091               46.0   LSHFO 0.5
3  39800000093               47.0   LSHFO 0.5
4  39800000095               46.0   LSHFO 0.5

In [ ]:
# 1° - igualar o nome sessionId para SESSION_ID em todas as bases

In [37]:
resultado_eventos_ID = resultado_eventos.rename(columns={'sessionId': 'SESSION_ID'})
resultado_eventos_ID.head()

,SESSION_ID,shipName,class,eventName,startGMTDate,endGMTDate,duration,distance,aftDraft,fwdDraft,...,displacement,beaufortScale,seaCondition,beaufortScaleDesc,seaConditionDesc,speed,speedGps,Porto,decLatitude,decLongitude
0,39800000084,DANIEL PEREIRA,Aframax,NAVEGACAO,2021-05-24 11:00:00,2021-05-25 11:00:00,24.0,282.0,14.9,14.0,...,128703.71,5.0,NaN,5 - Fresh breeze,3 - Slight,11.75,11.75,NaN,-32.1300,15.1300
1,39800000086,DANIEL PEREIRA,Aframax,NAVEGACAO,2021-05-25 11:00:00,2021-05-26 11:00:00,24.0,254.0,14.9,14.0,...,128703.72,NaN,NaN,3 - Gentle breeze,2 - Smooth (wavelets),10.58,10.58,NaN,-30.3800,10.2500
2,39800000088,DANIEL PEREIRA,Aframax,NAVEGACAO,2021-05-26 11:00:00,2021-05-27 12:00:00,25.0,295.0,14.9,14.0,...,128703.72,NaN,NaN,3 - Gentle breeze,3 - Slight,11.80,11.80,NaN,-28.5568,5.2018
3,39800000091,DANIEL PEREIRA,Aframax,NAVEGACAO,2021-05-27 12:00:00,2021-05-28 12:00:00,24.0,284.0,14.9,14.0,...,128703.72,NaN,NaN,3 - Gentle breeze,2 - Smooth (wavelets),11.83,11.83,NaN,-27.1400,0.2100
4,39800000093,DANIEL PEREIRA,Aframax,NAVEGACAO,2021-05-28 10:00:00,2021-05-29 11:00:00,25.0,293.0,14.9,14.0,...,128703.72,NaN,NaN,1 - Light air,2 - Smooth (wavelets),11.72,11.72,NaN,-25.2800,-4.4273

In [ ]:
# adicionar outro tratamento: embarcação em base_eventos é igual a shipName em base_consumo

In [41]:
resultado_eventos_consumo = resultado_consumo.merge(resultado_eventos_ID, on='SESSION_ID', how='inner')
resultado_eventos_consumo.head()

,SESSION_ID,CONSUMED_QUANTITY,DESCRIPTION,shipName,class,eventName,startGMTDate,endGMTDate,duration,distance,...,displacement,beaufortScale,seaCondition,beaufortScaleDesc,seaConditionDesc,speed,speedGps,Porto,decLatitude,decLongitude
0,39800000086,47.0,LSHFO 0.5,DANIEL PEREIRA,Aframax,NAVEGACAO,2021-05-25 11:00:00,2021-05-26 11:00:00,24.0,254.0,...,128703.72,NaN,NaN,3 - Gentle breeze,2 - Smooth (wavelets),10.58,10.58,NaN,-30.3800,10.2500
1,39800000088,48.0,LSHFO 0.5,DANIEL PEREIRA,Aframax,NAVEGACAO,2021-05-26 11:00:00,2021-05-27 12:00:00,25.0,295.0,...,128703.72,NaN,NaN,3 - Gentle breeze,3 - Slight,11.80,11.80,NaN,-28.5568,5.2018
2,39800000091,46.0,LSHFO 0.5,DANIEL PEREIRA,Aframax,NAVEGACAO,2021-05-27 12:00:00,2021-05-28 12:00:00,24.0,284.0,...,128703.72,NaN,NaN,3 - Gentle breeze,2 - Smooth (wavelets),11.83,11.83,NaN,-27.1400,0.2100
3,39800000093,47.0,LSHFO 0.5,DANIEL PEREIRA,Aframax,NAVEGACAO,2021-05-28 10:00:00,2021-05-29 11:00:00,25.0,293.0,...,128703.72,NaN,NaN,1 - Light air,2 - Smooth (wavelets),11.72,11.72,NaN,-25.2800,-4.4273
4,39800000095,46.0,LSHFO 0.5,DANIEL PEREIRA,Aframax,NAVEGACAO,2021-05-29 11:00:00,2021-05-30 11:00:00,24.0,282.0,...,128703.72,NaN,NaN,1 - Light air,5 - Rough,11.75,11.75,NaN,-23.4545,-9.2853

In [46]:
# que tipo de análise eu preciso agr?
# quero saber o consumo de combustível por tipo de embarcação

# preciso saber quais os tipos de shipName existem
resultado_eventos_consumo['shipName'].unique()

array(['DANIEL PEREIRA', 'ROMARIO SILVA', 'LUCAS MENDONÇA',
       'MARCOS CAVALCANTI', 'THIAGO FERNANDES', 'MARIA VALENTINA',
       'FÁBIO SANTOS', 'BRUNO LIMA', 'GISELLE CARVALHO',
       'VICTOR OLIVEIRA', 'CARLA SILVA', 'HENRIQUE ALVES', 'RAUL MARTINS',
       'RAFAEL SANTOS', 'RENATO GOMES', 'PAULO MOURA', 'RICARDO BARBOSA',
       'FELIPE RIBEIRO', 'GABRIELA MARTINS', 'RODRIGO PINHEIRO',
       'EDUARDO COSTA'], dtype=object)